---
# MinIO Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-config
  namespace: smap
type: Opaque
stringData:
  MINIO_ENDPOINT: 172.16.19.115:9000
  MINIO_ACCESS_KEY: smap
  MINIO_SECRET_KEY: hcmut2025
  MINIO_BUCKET: youtube-media
  MINIO_BUCKET_MODEL: youtube-media
  MINIO_USE_SSL: "False"
  MINIO_TARGET_PREFIX: "audios"
  MINIO_PRESIGNED_TTL: "600"
  MINIO_UPLOAD_PART_SIZE: "5242880"

---
# FFmpeg Service Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: ffmpeg-config
  namespace: smap
type: Opaque
stringData:
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  FFMPEG_PATH: "ffmpeg"
  FFMPEG_AUDIO_BITRATE: "192k"
  FFMPEG_TIMEOUT_SECONDS: "600"
  MAX_CONCURRENT_JOBS: "2"
