"""Create post_analytics table

Revision ID: dc8d02d16d50
Revises:
Create Date: 2025-11-29 12:56:04.144370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc8d02d16d50"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic command ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### command auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic command ###
