package redis

const (
	ONE_MINUTE     = 60
	FIVE_MINUTES   = ONE_MINUTE * 5
	TEN_MINUTES    = ONE_MINUTE * 10
	THIRTY_MINUTES = ONE_MINUTE * 30

	ONE_HOUR  = 3600
	TWO_HOURS = ONE_HOUR * 2
	ONE_DAY   = ONE_HOUR * 24

	PREFIX = "connect:"
)
