// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"strconv"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("sqlboiler: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type SubscriptionStatus string

// Enum values for SubscriptionStatus
const (
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusTrialing  SubscriptionStatus = "trialing"
	SubscriptionStatusPastDue   SubscriptionStatus = "past_due"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
	SubscriptionStatusExpired   SubscriptionStatus = "expired"
)

func AllSubscriptionStatus() []SubscriptionStatus {
	return []SubscriptionStatus{
		SubscriptionStatusActive,
		SubscriptionStatusTrialing,
		SubscriptionStatusPastDue,
		SubscriptionStatusCancelled,
		SubscriptionStatusExpired,
	}
}

func (e SubscriptionStatus) IsValid() error {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusTrialing, SubscriptionStatusPastDue, SubscriptionStatusCancelled, SubscriptionStatusExpired:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e SubscriptionStatus) Ordinal() int {
	switch e {
	case SubscriptionStatusActive:
		return 0
	case SubscriptionStatusTrialing:
		return 1
	case SubscriptionStatusPastDue:
		return 2
	case SubscriptionStatusCancelled:
		return 3
	case SubscriptionStatusExpired:
		return 4

	default:
		panic(errors.New("enum is not valid"))
	}
}
