apiVersion: v1
kind: Service
metadata:
  name: smap-playwright
  namespace: smap
  labels:
    app: smap-playwright
    component: service
    version: v3
spec:
  type: ClusterIP
  selector:
    app: smap-playwright
  ports:
  - name: websocket
    port: 4444
    targetPort: websocket
    protocol: TCP
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service-headless
  namespace: smap
  labels:
    app: smap-playwright
    component: service-headless
    version: v3
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: smap-playwright
  ports:
  - name: websocket
    port: 4444
    targetPort: websocket
    protocol: TCP
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP